### ISSUE TITLE
Failure to download books

### ISSUE THREAD

**Issue by ddanese** [vladimyr/packtpub-downloader#1]
This just started today, as far as I can tell.

 Writing to "Oracle Advanced PL/SQL Developer Professional Guide.epub" ...  stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, open 'Oracle Advanced PL/SQL Developer Professional Guide.epub'
    at Error (native)

**Comment by vladimyr** [comment]
Hey,

thanks for reporting the issue. I'm not actively using it so haven't
noticed. Currently I have limited time to play with open source things so
if you have any node/js experience feel free to play around it hopefully
ending in successful solution aka pull request. Anyway I'll try to check it
out asap but don't expect anything before at least next weekend :(

**Comment by ddanese** [comment]
Closing this.  Looks like it was an issue with something in the page.  It resolved itself.
